Models/Firm.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Drawing;
using System.IO;

namespace PCI_Website_2018.Models
{
    public class Firm
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Bio { get; set; }
        public string College { get; set; }
        public string Degree { get; set; }
        public string ImgURL { get; set; }
    }
}

Controllers/FirmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PCI_Website_2018.Models;
using System.IO;
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;
using System.Drawing;

namespace PCI_Website_2018.Controllers
{
    public class FirmController : Controller
    {
        private readonly FirmContext _context;

        public FirmController(FirmContext context)
        {
            _context = context;
        }
        public Firm firm { get; set; }
        // GET: Firm
        public async Task<IActionResult> Index(int id)
        {    
            //for nav active states – so know which page
            ViewData["Active"] = "Firm";
            //******************************************

            //routing from contact page ...
            if (id == 1 )
            {
                //in view...if data is not "" then display contact link in nav tree, otherwise show firm link ...
                ViewData["Contact"] = "x";
            }     

            var firm = await _context.Firm
                .OrderBy(m => m.LastName)
                .ToListAsync();

            if (firm == null)
            {
                TempData["Error"] = "firm"; //for error message tailored to user
                return RedirectToAction("Error");
            }

            return View(firm);
        }
        public async Task<IActionResult> Firm_IP(int id)
        {
            //for nav active states – so know which page
            ViewData["Active"] = "Firm";
            //******************************************

            //routing from contact page ...
            if (id == 1 )
            {
                //in view...if data is not "" then display contact link in nav tree, otherwise show firm link ...
                ViewData["Contact"] = "x";
            }     

            var firm = await _context.Firm
            .Where(m => m.Title.Contains("Investment Partner"))
                .OrderBy(m => m.LastName)
                .ToListAsync();

            if (firm == null)
            {
                TempData["Error"] = "firm"; //for error message tailored to user
                return RedirectToAction("Error");
            }

            return View(firm);
        }
        public async Task<IActionResult> Firm_President(int id)
        {
            //for nav active states – so know which page
            ViewData["Active"] = "Firm";
            //******************************************

            //routing from contact page ...
            if (id == 1 )
            {
                //in view...if data is not "" then display contact link in nav tree, otherwise show firm link ...
                ViewData["Contact"] = "x";
            }       

            var firm = await _context.Firm
            .Where(m => m.Title.Contains("President & CEO"))
                .OrderBy(m => m.LastName)
                .ToListAsync();

            if (firm == null)
            {
                TempData["Error"] = "firm"; //for error message tailored to user
                return RedirectToAction("Error");
            }

            return View(firm);
        }
        public async Task<IActionResult> Firm_Finance(int id)
        {
            //for nav active states – so know which page
            ViewData["Active"] = "Firm";
            //******************************************

            //routing from contact page ...
            if (id == 1 )
            {
                //in view...if data is not "" then display contact link in nav tree, otherwise show firm link ...
                ViewData["Contact"] = "x";
            }     

            var firm = await _context.Firm
            .Where(m => m.Title.Contains("Structured Finance Partner") 
            || m.LastName.Contains("Sedar") 
            || m.LastName.Contains("Arnold"))
                .OrderBy(m => m.LastName)
                .ToListAsync();

                foreach (var record in firm) {
                    if (record.Title == "Investment Partner")
                    {
                        record.Title = "Structured Finance Partner";
                    }
                }

            if (firm == null)
            {
                TempData["Error"] = "firm"; //for error message tailored to user
                return RedirectToAction("Error");
            }

            return View(firm);
        }
        public async Task<IActionResult> Firm_Operations(int id)
        {
            //for nav active states – so know which page
            ViewData["Active"] = "Firm";
            //******************************************

            //routing from contact page ...
            if (id == 1 )
            {
                //in view...if data is not "" then display contact link in nav tree, otherwise show firm link ...
                ViewData["Contact"] = "x";
            }     

            var firm = await _context.Firm
                .Where(m => m.Title.Contains("Graphic") 
                || m.Title.Contains("Photo") 
                || m.Title.Contains("Logistics") 
                || m.Title.Contains("Production") 
                || m.Title.Contains("Technology"))
                .OrderBy(m => m.LastName)
                .ToListAsync();

        if (firm == null)
            {
                TempData["Error"] = "firm"; //for error message tailored to user
                return RedirectToAction("Error");
            }

            return View(firm);
        }
        public async Task<IActionResult> Input()
        {
            return View(await _context.Firm.ToListAsync());
        }

        // GET: Firm/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var firm = await _context.Firm
                .FirstOrDefaultAsync(m => m.ID == id);
            if (firm == null)
            {
                return NotFound();
            }

            return View(firm);
        }
         // GET: Firm/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Firm/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,FirstName,LastName,FullName,Title,Email,Phone,Bio,College,Degree,ImgURL")] Firm firm)
        {
            if (ModelState.IsValid)
            {
                _context.Add(firm);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Input));
            }
            return View(firm);
        }

        // GET: Firm/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var firm = await _context.Firm.FindAsync(id);
            if (firm == null)
            {
                return NotFound();
            }
            return View(firm);
        }

        // POST: Firm/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,FirstName,LastName,FullName,Title,Email,Phone,Bio,College,Degree,ImgURL")] Firm firm)
        {
            if (id != firm.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(firm);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FirmExists(firm.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Input));
            }
            return View(firm);
        }

        // GET: Firm/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var firm = await _context.Firm
                .FirstOrDefaultAsync(m => m.ID == id);
            if (firm == null)
            {
                return NotFound();
            }

            return View(firm);
        }

        // POST: Firm/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var firm = await _context.Firm.FindAsync(id);
            _context.Firm.Remove(firm);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Input));
        }

        private bool FirmExists(int id)
        {
            return _context.Firm.Any(e => e.ID == id);
        }
    }
}

ViewComponents/ClientsReferencesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PCI_Website_2018.Models;

namespace PCI_Website_2018.ViewComponents
{
    public class ClientsReferencesViewComponent : ViewComponent
    {
        private readonly ClientsReferencesContext _contextR;

        public ClientsReferencesViewComponent(ClientsReferencesContext context)
        {
            _contextR = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(string searchString)
        {
            
            var references = from m in _contextR.ClientReferences
                 select m;
                //get clients dataset
                references = references.Where(s => s.RefCompany.Contains(searchString)
                || s.RefFullname.Contains(searchString));

                
            return View(await references.ToListAsync());
        }
    }
}

ViewComponents/ClientsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PCI_Website_2018.Models;

namespace PCI_Website_2018.ViewComponents
{
    public class ClientsViewComponent : ViewComponent
    {
        private readonly ClientsContext _contextC;

        public ClientsViewComponent(ClientsContext context)
        {
            _contextC = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(string searchString)
        {
            
            var clients = from m in _contextC.ClientList
                 select m;
                //get clients dataset
                clients = clients.Where(s => s.CrfCompany.Contains(searchString));

                
            return View(await clients.ToListAsync());
        }
    }
}

ViewComponents/TransactionsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PCI_Website_2018.Models;

namespace PCI_Website_2018.ViewComponents
{
    public class TransactionsViewComponent : ViewComponent
    {
        private readonly TransactionsContext _contextT;

        public TransactionsViewComponent(TransactionsContext context)
        {
            _contextT = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(string searchString)
        {
            string searchStringSingle = " " + searchString + " ";
                 var transactions = from m in _contextT.WebsiteTransactions
                 select m;
                //get transactions dataset
                transactions = transactions.Where(s => s.WtrName.Contains(searchStringSingle)
                || s.WtrType.Contains(searchString)
                || s.WtrState.Contains(searchString)
                || s.WtrCity.Contains(searchString)
                || s.WtrDescription.Contains(searchStringSingle));

                
            return View(await transactions.ToListAsync());
        }
    }
}

Views/Shared/_Firm.cshtml
@model IEnumerable<PCI_Website_2018.Models.Firm>

@{
    string str = Convert.ToString(@ViewData["Contact"]);
}


 
<div class="container-fluid padding-tb" id="mid-home-bg">
   <div class="container narrow">

     <!-- nav tree ... -->
     <div class="row padding-tb-md">
         <div class="col-lg-12 xs-no-padding">
             @{
                 if (str == "") //if routed from main nav
                 {
                    <h5 class="text-muted"><a asp-area="" asp-controller="Home" asp-action="Index">Palmer Capital Inc</a> &nbsp;&rsaquo;&nbsp; <a asp-area="" asp-controller="Firm" asp-action="Index">The Firm</a> &nbsp;&rsaquo;&nbsp; @ViewData["SubTitle"]</h5>
                    <hr class="hr-trans" />
                 }
                 else //if routed from contact us or quicklinks
                 {
                    <h5 class="text-muted"><a asp-area="" asp-controller="Home" asp-action="Index">Palmer Capital Inc</a> &nbsp;&rsaquo;&nbsp; <a asp-area="" asp-controller="Home" asp-action="Contact">Contact Us</a> &nbsp;&rsaquo;&nbsp; @ViewData["SubTitle"]</h5>
                    <hr class="hr-trans" />
                 }
             }
         </div>
     </div>  

     <div class="btn-group btn-group-justified margin-tb" role="group" aria-label="...">
             @{
                 if (str == "") //if routed from main nav
                 {
                    <a class="btn btn-nav" asp-route-id="0" asp-controller="Firm" asp-action="Index" id="Index">Full Team</a>
                    <a class="btn btn-nav" asp-route-id="0" asp-controller="Firm" asp-action="Firm_President" id="Firm_President">President</a>
                    <a class="btn btn-nav" asp-route-id="0" asp-controller="Firm" asp-action="Firm_IP" id="Firm_IP">Investments</a>
                    <a class="btn btn-nav" asp-route-id="0" asp-controller="Firm" asp-action="Firm_Finance" id="Firm_Finance">Finance</a>
                    <a class="btn btn-nav" asp-route-id="0" asp-controller="Firm" asp-action="Firm_Operations" id="Firm_Operations">Operations</a>
                 }
                 else //if routed from contact us or quicklinks
                 {
                    <a class="btn btn-nav" asp-route-id="1" asp-controller="Firm" asp-action="Index" id="Index">Full Team</a>
                    <a class="btn btn-nav" asp-route-id="1" asp-controller="Firm" asp-action="Firm_President" id="Firm_President">President</a>
                    <a class="btn btn-nav" asp-route-id="1" asp-controller="Firm" asp-action="Firm_IP" id="Firm_IP">Investments</a>
                    <a class="btn btn-nav" asp-route-id="1" asp-controller="Firm" asp-action="Firm_Finance" id="Firm_Finance">Finance</a>
                    <a class="btn btn-nav" asp-route-id="1" asp-controller="Firm" asp-action="Firm_Operations" id="Firm_Operations">Operations</a>
                 }
             }
           

       </div>
    

    <div id="progress" class="padding-tb-md text-center">
        <img src="/images/loading.gif" alt="" />
    </div>

    <div id="result">
        <hr />
        @foreach (var item in Model) 
            {
                    <div class="row">
                        <!-- pictures ... if we ever add back..change cols below from 12 to 9 (e.g. col-lg-12 TO col-lg-9) -->
                        <!-- <div class="col-lg-3 col-md-3 col-sm-3 text-center">
                            <img src="@Url.Content("~/images/TeamPhotos/" + item.ImgURL)" class="resume-photo" />
                        </div> -->
                        <div class="col-lg-12 col-md-12 col-sm-12 xs-no-padding">
                            <h4 class="resume-header">@Html.DisplayFor(modelItem => item.FirstName)&nbsp;@Html.DisplayFor(modelItem => item.LastName) &ndash; @Html.DisplayFor(modelItem => item.Title)</h4>
                            <p><a href="mailto:@Html.DisplayFor(modelItem => item.Email)">@Html.DisplayFor(modelItem => item.Email)</a></p>
                            <p><a href="tel:@Html.DisplayFor(modelItem => item.Phone)">@Html.DisplayFor(modelItem => item.Phone)</a></p>
                            <p>@Html.DisplayFor(modelItem => item.Bio)</p>
                            <h5>@Html.DisplayFor(modelItem => item.College)</h5>
                            <h6>@Html.DisplayFor(modelItem => item.Degree)</h6>
                        </div>
                    </div>  <!-- end row -->
                    <hr />
            }   
    </div>  <!-- end result -->

Views/Shared/_FirmJumbo.cshtml
    <div class="jumbotron padding-tb-xl padding-xs-tb-lg text-center" id="jumbotron-firm-bg">
        <div class="container narrow">
            <div class="row">
                    <h1>@ViewData["Title"]</h1>
                    <h4 class="text-capitalize">@ViewData["SubTitle"]</h4>
            </div>
        </div>
    </div>

Views/Shared/_QuickLinks.cshtml
            <div class="row padding-tb-md">
                <div class="col-md-4 col-sm-4 xs-font-lg">  
                    <h4>Quick Links:</h4>
                    <a asp-area="" asp-controller="Home" asp-action="Index">Home Page</a><br />
                    <a asp-area="" asp-controller="Home" asp-action="About">About Us</a><br />
                    <a asp-area="" asp-controller="Firm" asp-action="Index">The Firm</a><br />
                    <a asp-area="" asp-controller="Transactions" asp-action="Index">All Transactions</a><br />
                    <a asp-area="" asp-controller="Home" asp-action="Clients">Clients</a><br />
                    <a asp-area="" asp-controller="Home" asp-action="Contact">Contact Us</a>
                </div>
                <div class="col-md-4 col-sm-4 xs-font-lg">  
                    <address>
                        <h4>Contact Us Directly:</h4>
                            <a asp-route-id="1" asp-controller="Firm" asp-action="Firm_President">President &amp; CEO</a><br />
                            <a asp-route-id="1" asp-controller="Firm" asp-action="Firm_IP">Investment Partners</a><br />
                            <a asp-route-id="1" asp-controller="Firm" asp-action="Firm_Finance">Structured Finance Partners</a><br />
                            <a asp-route-id="1" asp-controller="Firm" asp-action="Firm_Operations">Operations</a>
                    </address>  
                </div>
                <div class="col-md-4 col-sm-4 xs-font-lg">  
                    <address>
                        <h4>Additional Info:</h4>
                            <a href="http://www.palmercapital.com/googlemaps.html" target="_blank">Map</a><br />
            				<a target="_blank" class="darkBlue" href="https://roundme.com/tour/248326/view/727101">PCI Tour</a>
                    </address>
                </div>
                <div class="row padding-tb-md"></div> <!-- for extra space -->
            </div>

Views/Shared/_Search.cshtml
@using System.Web;
@using Microsoft.Extensions.WebEncoders;
@using System.Text.Encodings.Web;

@{
    ViewData["Title"] = "Search Results";
    ViewData["SearchTitle"] = "PCI website";
    //changes nav tree text
}

    @await Html.PartialAsync("_SearchJumbo")

    <div class="container-fluid padding-tb" id="mid-home-bg">
        <div class="container narrow xs-no-padding">

            <!-- top nav tree ... -->
            <div class="row padding-top-md">
                <div class="col-lg-12">
                    <h5 class="text-muted"><a asp-area="" asp-controller="Home" asp-action="Index">Palmer Capital Inc</a> &nbsp;&rsaquo;&nbsp; @ViewData["Title"] </h5>
                    <hr class="hr-trans" />
                </div>
            </div> 
            
            <div class="row">
                <form class="navbar-form search searchResult" role="search" asp-controller="Home" asp-action="Search">
                    <div class="form-group searchResult">
                    <div class="input-group search searchResult">
                        <input type="text" class="form-control search searchResult focus" value="@ViewData["Search"]" name="SearchString" />
                        <span class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="material-icons icon-search">search</i></button>
                        </span>
                        </div>
                    </div>
                        @{                        
                            var count = Convert.ToInt32(@ViewData["Count"]);
                            if (count > 1) 
                            {
                                <h5 class="text-muted">@ViewData["Count"] results found in @ViewData["SearchTitle"].</h5>      
                            }
                            else
                            {
                                <h5 class="text-muted">@ViewData["Count"] result found in @ViewData["SearchTitle"].</h5>
                            }
                        }
                </form>
            </div>
                @{
                    //FIRM RESULTS
                    var countF = Convert.ToInt32(@ViewData["FirmCount"]);
                    if (countF > 0)
                    {  
                        @await Component.InvokeAsync("Firm", new { searchString = ViewData["Search"] } ); 
                    }
                }  

                @{
                    //CLIENTS RESULTS
                    var countC = Convert.ToInt32(@ViewData["ClientsCount"]);
                    if (countC > 0)
                    { 
                        @await Component.InvokeAsync("Clients", new { searchString = ViewData["Search"] } );    
                    }
                }

                @{
                    //REFERENCES RESULTS
                    var countR = Convert.ToInt32(@ViewData["RefCount"]);
                    if (countR > 0)
                    {
                        @await Component.InvokeAsync("ClientsReferences", new { searchString = ViewData["Search"] } );
                    }
                }    

                @{
                    //TRANSACTIONS RESULTS
                    var countT = Convert.ToInt32(@ViewData["TransactionsCount"]);
                    if (countT > 0)
                    {
                        @await Component.InvokeAsync("Transactions", new { searchString = ViewData["Search"] } );
                    }
                }
            
            @await Html.PartialAsync("_QuickLinks")
        </div>
    </div>

Views/Shared/_SearchJumbo.cshtml
<div class="jumbotron padding-tb-xl padding-xs-tb-lg text-center" id="jumbotron-about-bg">
    <div class="container narrow">
        <div class="row">
                <h1>@ViewData["Title"]</h1>
                <h4 class="text-capitalize">PCI Website</h4>
        </div>
    </div>
</div>

Views/Shared/_SearchNull.cshtml
@{
    ViewData["Title"] = "Search Results";
    ViewData["SearchTitle"] = "PCI website";
    //changes nav tree text
}

    @await Html.PartialAsync("_SearchJumbo")

    <div class="container-fluid padding-tb" id="mid-home-bg">
        <div class="container narrow xs-no-padding">

            <!-- top nav tree ... -->
            <div class="row padding-top-md">
                <div class="col-lg-12">
                    <h5 class="text-muted"><a asp-area="" asp-controller="Home" asp-action="Index">Palmer Capital Inc</a> &nbsp;&rsaquo;&nbsp; @ViewData["Title"] </h5>
                    <hr class="hr-trans" />
                </div>
            </div> 

            <div class="row">
                <form class="navbar-form search searchResult" role="search" asp-controller="Home" asp-action="Search">
                    <div class="form-group searchResult">
                    <div class="input-group search searchResult">
                        <input type="text" class="form-control search searchResult focus" autocomplete="off" value="@ViewData["Search"]" name="SearchString" />
                        <span class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="material-icons icon-search">search</i></button>
                        </span>
                        </div>
                    </div>
                    <h5 class="text-muted">No results found in PCI Website.</h5>
                </form>
            </div>
            
            <div class="row">
                <div class="col-lg-12">
                    @{
                        if (ViewData["Search"] == null)
                        {
                            <h4>Please enter a search term.</h4>
                            <h5>Tip: try searching for a team member or transaction.</h5>
                        }
                        else
                        {
                            <h4>Sorry, no results matching "@ViewData["Search"]" were found.</h4>
                            <h5>Tip: try searching for a team member or transaction.</h5>
                        }
                    }
                </div>
            </div>
            <div class="row padding-tb-md">
                <div class="col-lg-12">
                    <hr class="hr-trans" />
                </div>
            </div>
            @await Html.PartialAsync("_QuickLinks")
         </div>
    </div>

Views/Shared/_SearchTransNull.cshtml
@{
    ViewData["Title"] = "Search Results";
}

@section Scroll
{
<style type="text/css">
    html { overflow-y: scroll; }
</style>
}

@await Html.PartialAsync("_Transactions")

@section Top {
    <div class="top" title="scroll to top">
    <button type="button" class="btn btn-sm btn-default">
        <i class="material-icons icon-lg">arrow_upward</i>
    </button>
    </div>
}

@section scripts {
    <environment include="Development">
        <script src="~/js/transactions.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/transactions.js" asp-append-version="true"></script>
    </environment>
}